apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gazzopar-app
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
  source:
    path: .
    repoURL: 'https://github.com/Gazzopar/gazzopar_website.git'
    targetRevision: main
