Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine318"

  config.vm.provision "shell", inline: <<-SHELL
	  apk update
	  apk add curl
  SHELL

  config.vm.define "vvioviS" do |control|
	control.vm.hostname = "vvioviS"
	control.vm.network "private_network", ip: "192.168.56.110"
	control.vm.provider "virtualbox" do |vb|
		vb.memory = "512"
		vb.cpus = 1
		vb.name = "vvioviS"
	end
	control.vm.provision "shell", path: "vvioviS.sh"
  end
  config.vm.define "vvioviSW" do |control|
	control.vm.hostname = "vvioviSW"
	control.vm.network "private_network", ip: "192.168.56.111"
	control.vm.provider "virtualbox" do |vb|
		vb.memory = "512"
		vb.cpus = 1
		vb.name = "vvioviSW"
	end
	control.vm.provision "shell", path: "vvioviSW.sh"
  end

end
