Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine319"

  config.vm.provision "shell", inline: <<-SHELL
	  apk update && apk add --no-cache curl
  SHELL

  config.vm.define "vvioviS" do |control|
	control.vm.hostname = "vvioviS"
	control.vm.network "private_network", ip: "192.168.56.110"
	control.vm.provider "libvirt" do |libvirt|
		libvirt.memory = "3072"
		libvirt.cpus = 2
	end
	control.vm.provision "shell", path: "vvioviS.sh"
  end
  config.vm.define "vvioviSW" do |control|
	control.vm.hostname = "vvioviSW"
	control.vm.network "private_network", ip: "192.168.56.111"
	control.vm.provider "libvirt" do |libvirt|
		libvirt.memory = "2048"
		libvirt.cpus = 1
	end
	control.vm.provision "shell", path: "vvioviSW.sh"
  end

end
