# Minimal settings
global:
  edition: ce
  ingress:
    enabled: false
    configureCertmanager: false
  hosts:
    domain: 172.18.0.2.nip.io
    externalIP: 172.18.0.2
  # Disable Rails bootsnap cache (temporary)
  rails:
    bootsnap:
      enabled: false
  shell:
    # Configure the clone link in the UI to include the high-numbered NodePort
    # value from below (`gitlab.gitlab-shell.service.nodePort`)
    port: 32022
# Don't use certmanager, we'll self-sign
certmanager:
  install: false
# Use the `ingress` addon, not our Ingress (can't map 22/80/443)
nginx-ingress:
  enabled: false
# Save resources, only 3 CPU
prometheus:
  install: false
gitlab-runner:
  install: false
# Reduce replica counts, reducing CPU & memory requirements
gitlab:
  webservice:
    minReplicas: 1
    maxReplicas: 1
    ingress:
      enabled: true
      annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure  # Utilisez 'websecure' pour HTTPS ou 'web' pour HTTP
          traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
        - "gitlab.172.18.0.2.nip.io"  # Remplacez par votre sous-domaine pour GitLab
      paths:
        - "/"
  sidekiq:
    minReplicas: 1
    maxReplicas: 1
  gitlab-shell:
    minReplicas: 1
    maxReplicas: 1
    # Map gitlab-shell to a high-numbered NodePort to support cloning over SSH since
    # Minikube takes port 22.
    service:
      type: NodePort
      nodePort: 32022
registry:
  hpa:
    minReplicas: 1
    maxReplicas: 1
