apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3-deployment
  labels:
    app: app3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
      - name: app3
        image: nginx:1.27.2-alpine
        ports:
        - containerPort: 80
        volumeMounts:
          - name: app3-index-volume
            mountPath: /usr/share/nginx/html/index.html
            subPath: index.html
          - name: app3-images-volume
            mountPath: /usr/share/nginx/html/images
      volumes:
      - name: app3-index-volume
        configMap:
          name: app3-index
      - name: app3-images-volume
        configMap:
          name: app3-static-content

